spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qrsignin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1634
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      min-idle: 8

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp




mybatis:
  type-aliases-package: com.ymr.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 80


